### ISSUE TITLE
Incorrect Formula for the Derivative 

### ISSUE THREAD

**Issue by UPstartDeveloper** [Make-School-Courses/QL-1.1#1]
In class 8, "Finding the Max/Min of a Function" there's an incorrect formulation of the derivative.
In the left-hand side of the equation, the change in x is given as the numerator, yet after the equals sign it is then in the denominator. 

I think that's a mistake and it should be flipped. It looks like this currently: 
![Screenshot of incorrect formula](https://i.postimg.cc/nLHWjxkP/Screen-Shot-2020-03-31-at-11-41-56-AM.png)

**Comment by ibirnam** [comment]
@UPstartDeveloper - thanks for catching this mistake! We've updated it in our [latest commit](https://github.com/Make-School-Courses/QL-1.1-Quantitative-Reasoning/commit/2f6d05aaec97f6dec3e54a6af9fa5a9836a27c6f)
